<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
        <RootNamespace>db_restore_tool</RootNamespace>
        <AssemblyName>db_restore_tool</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.3" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.3" />
        <PackageReference Include="Microsoft.SqlServer.SqlManagementObjects" Version="181.15.0" />
        <PackageReference Include="System.CommandLine" Version="2.0.3" />
    </ItemGroup>

    <ItemGroup>
        <!-- Embed the zip folder content for logic that expects resources -->
        <EmbeddedResource Include="zip\**" />
    </ItemGroup>

</Project>
